apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      serviceAccountName: default
      containers:
        - image: nginx/nginx-ingress:1.5.6
          imagePullPolicy: Always
          name: nginx-ingress
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - -nginx-configmaps=default/nginx-config
            - -default-server-tls-secret=default/nginx-ingress-ssl-cert
            - -v=3 # Enables extensive logging. Useful for troubleshooting.
            - -report-ingress-status
            - -external-service=nginx-ingress
            - -enable-leader-election
            #- -enable-prometheus-metrics
            #- -enable-custom-resources
